version: '3.4'

networks:
  demoapp:
  demoui:

services:
 db:
  container_name: app-db
  image: mcr.microsoft.com/mssql/server:2019-latest 
  ports:
   - 8002:1433
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=KNpro0987@
  networks:
   - demoapp
 serverapp:
  container_name: demo-server-app
  image: ${DOCKER_REGISTRY-}serverapp
  build:
   context: .
   dockerfile: ServerApp/Dockerfile
  ports:
   - 8001:80 
  depends_on:
   - db
  environment:
   - DB_HOST=db
   - DB_NAME=APICURD
   - DB_SA_PASSWORD=KNpro0987@
  networks:
   - demoapp
   - demoui
 webapp:
  container_name: frontend
  image: ${DOCKER_REGISTRY-}frontend
  ports:
   - 8003:4200
  build:
   context: frontend
   dockerfile: Dockerfile
  depends_on:
   - serverapp
  networks:
   - demoui
